-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 12, 2023 at 06:06 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_laravelblog1`
--

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(3, '2022_11_05_053014_tbl_category', 1),
(4, '2022_11_07_105249_tbl_post_migration', 2);

-- --------------------------------------------------------

--
-- Table structure for table `personal_access_tokens`
--

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `tbl_category`
--

CREATE TABLE `tbl_category` (
  `id` int(10) UNSIGNED NOT NULL,
  `catName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `catImg` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `post` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `tbl_category`
--

INSERT INTO `tbl_category` (`id`, `catName`, `catImg`, `created_at`, `updated_at`, `post`) VALUES
(12, 'PHP', '1667808106.PNG', '2022-11-07 02:01:46', '2022-11-14 00:27:07', 9),
(13, 'Java', '1667808120.jpg', '2022-11-07 02:02:00', '2022-11-14 01:06:41', 10),
(25, 'MYSQL', '1668403740.png', '2022-11-13 23:29:00', '2022-11-14 01:00:11', 5),
(26, 'CSS', '1668403757.png', '2022-11-13 23:29:17', '2022-11-14 01:02:52', 4),
(27, 'Html', '1668403815.jpg', '2022-11-13 23:30:15', '2022-11-14 01:04:27', 2),
(28, 'Javascript', '1668403883.jpg', '2022-11-13 23:30:46', '2022-11-13 23:31:23', 0),
(29, 'Python', '1668403907.png', '2022-11-13 23:31:47', '2022-11-13 23:31:47', 0),
(30, 'C#', '1668403933.PNG', '2022-11-13 23:32:13', '2022-11-13 23:32:13', 0);

-- --------------------------------------------------------

--
-- Table structure for table `tbl_comment`
--

CREATE TABLE `tbl_comment` (
  `id` int(11) NOT NULL,
  `postId` varchar(255) NOT NULL,
  `userId` varchar(255) NOT NULL,
  `userName` varchar(255) NOT NULL,
  `userEmail` varchar(255) NOT NULL,
  `userWebsite` varchar(255) DEFAULT NULL,
  `userImg` varchar(255) DEFAULT NULL,
  `text` text NOT NULL,
  `date` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `tbl_comment`
--

INSERT INTO `tbl_comment` (`id`, `postId`, `userId`, `userName`, `userEmail`, `userWebsite`, `userImg`, `text`, `date`) VALUES
(1, '31', '', 'Munaim Khan', '', NULL, '', 'This is a good useful article. This is a good useful article. This is a good useful article. This is a good useful article. This is a good useful article. This is a good useful article. This is a good useful article. This is a good useful article. This is a good useful article. This is a good useful article. This is a good useful article. This is a good useful article. \r\nThis is a good useful article. This is a good useful article. This is a good useful article. ', '2022-11-10 00:00:00'),
(3, '29', '', 'Rashedul Karim', '', NULL, '', 'This is post comment. This is post comment. This is post comment. This is post comment. This is post comment. This is post comment. This is post comment. This is post comment. This is post comment. This is post comment. This is post comment. This is post comment. This is post comment. ', '2022-11-10 19:08:57'),
(5, '31', '4', 'Samiul Alam', 'samiul@gmail.com', 'ww.com', NULL, '<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.</p> \r\n\r\n<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.</p> \r\n\r\n<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.</p>', '2022-11-11 11:47:00'),
(8, '31', '', 'Raihanul Ikram', 'raihan@gmail.com', NULL, NULL, 'Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.', '2022-11-11 12:04:33'),
(9, '31', '4', 'Samiul Islam', 'samiul@gmail.com', NULL, NULL, '<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. <b>Multiple Update</b></p>', '2022-11-11 12:25:09'),
(11, '29', '1', 'Munaim Khan', 'khanmail2599@gmail.com', NULL, NULL, 'good post this is', '2022-11-12 18:47:24');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_message`
--

CREATE TABLE `tbl_message` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `message` mediumtext NOT NULL,
  `date` datetime NOT NULL DEFAULT current_timestamp(),
  `status` tinyint(4) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `tbl_message`
--

INSERT INTO `tbl_message` (`id`, `name`, `email`, `phone`, `subject`, `message`, `date`, `status`) VALUES
(2, 'Rashedul Karim', 'rashed@gmail.com', '01832-457890', 'My new message', 'My message is here. My message is here. My message is here. My message is here. My message is here. My message is here. My message is here. My message is here. My message is here. My message is here. My message is here. \r\n\r\nMy message is here. My message is here. My message is here. My message is here. My message is here. My message is here. My message is here. ', '2022-11-13 10:54:33', 1),
(3, 'Kayes Ahmed', 'kayes@gmail.com', '01432-345465', 'new contact message', 'Hi, i am Kayes Ahmed. This is my new contact message. I want to know about your reknown company. Hi, i am Kayes Ahmed. This is my new contact message. I want to know about your reknown company. Hi, i am Kayes Ahmed. This is my new contact message. I want to know about your reknown company. \r\n\r\nHi, i am Kayes Ahmed. This is my new contact message. I want to know about your reknown company. Hi, i am Kayes Ahmed. This is my new contact message. I want to know about your reknown company. \r\n\r\nHi, i am Kayes Ahmed. This is my new contact message. I want to know about your reknown company.', '2022-11-13 21:41:55', 1),
(4, 'Kayes Ahmed', 'kayes@gmail.com', '1826116163', 'new contact message', 'This is another new contact test message. This is another new contact test message. This is another new contact test message. This is another new contact test message. This is another new contact test message. This is another new contact test message. \r\n\r\nThis is another new contact test message. This is another new contact test message. This is another new contact test message. \r\n\r\nThis is another new contact test message. This is another new contact test message. This is another new contact test message. This is another new contact test message.', '2022-11-13 21:43:25', 1),
(5, 'Rafiul Islam', 'rafi@gmail.com', '01826116163', 'Reply to your new message', 'I am Rafiul Islam. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content.', '2022-11-14 19:21:47', 0),
(6, 'Tahirul Haq', 'tahir@gmail.com', '1826116163', 'Reply to your new message', 'This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content.', '2022-11-14 19:22:22', 0),
(7, 'Rabiul Islam', 'rabi@gmail.com', '1826116163', 'Reply to your new message', 'This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content.', '2022-11-14 19:22:39', 1),
(8, 'Muhit Rahman', 'muhit@yahoo.com', '1826116163', 'new contact message', 'This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content.', '2022-11-14 19:23:04', 0),
(9, 'Rahi taufuq', 'rahi@gmail.com', '1826116163', 'Reply to your new message', 'This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content.', '2022-11-14 19:23:28', 1),
(10, 'Emdadul Islam', 'emdad@gmail.com', '01826116163', 'Reply to your new message', 'This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content.', '2022-11-14 19:24:04', 0),
(11, 'Umar Faruk', 'faruk@hotmail.com', '01826116163', 'new contact message', 'This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content.', '2022-11-14 19:24:31', 0),
(12, 'Md. Munaim Khan', 'khanmail2599@gmail.com', '01826116163', 'Reply to your new message', 'This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content.', '2022-11-14 19:24:39', 0),
(13, 'Naim Islam', 'naim@gamil.om', '01826116163', 'Reply to your new message', 'This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content. This is my message content.', '2022-11-14 19:25:00', 0),
(14, 'Md. Munaim Khan', 'khanmail2599@gmail.com', '01826116163', 'Reply to your new message', 'new contact', '2022-11-14 20:12:41', 1),
(15, 'Md. Munaim Khan', 'khanmail2599@gmail.com', '01826116163', 'Reply to your new message', 'content', '2022-11-14 20:23:47', 0),
(16, 'Md. Munaim Khan', 'khanmail2599@gmail.com', '01826116163', 'Reply to your new message', 'new', '2022-11-14 20:24:34', 0),
(17, 'Md. Munaim Khan', 'khanmail2599@gmail.com', '01826116163', 'Reply to your new message', '3eefd', '2022-11-14 20:27:08', 0);

-- --------------------------------------------------------

--
-- Table structure for table `tbl_post`
--

CREATE TABLE `tbl_post` (
  `id` int(10) UNSIGNED NOT NULL,
  `posttitle` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `postcontent` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postImg` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `catId` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postedby` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `posttime` datetime NOT NULL DEFAULT current_timestamp(),
  `posttags` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postview` int(11) NOT NULL DEFAULT 0,
  `poststatus` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `tbl_post`
--

INSERT INTO `tbl_post` (`id`, `posttitle`, `postcontent`, `postImg`, `catId`, `postedby`, `posttime`, `posttags`, `postview`, `poststatus`) VALUES
(37, 'PHP post 1', 'Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668406886.png', '12', '1', '2022-11-14 12:21:26', 'php, post', 2, '1'),
(38, 'PHP post 2', 'Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668406923.png', '12', '1', '2022-11-14 12:22:03', 'php, post', 0, '1'),
(39, 'PHP post 3', 'Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668406952.jpg', '12', '1', '2022-11-14 12:22:32', 'php, post', 0, '1'),
(40, 'PHP post 4', 'Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668407021.jpg', '12', '3', '2022-11-14 12:23:41', 'java, post, text, new, my', 0, '1'),
(41, 'PHP post 5', 'Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668407061.jpg', '12', '3', '2022-11-14 12:24:21', 'php, post', 0, '1'),
(42, 'PHP post 6', 'Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668407088.jpg', '12', '3', '2022-11-14 12:24:48', 'php, post, text, new, my', 0, '1'),
(43, 'PHP', 'Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668407177.jpg', '12', 'Munaim Khan', '2022-11-14 12:26:17', 'php,', 0, '0'),
(44, 'PHP post 8', 'Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668407201.jpg', '12', '5', '2022-11-14 12:26:41', 'php, post, text, new, my', 0, '1'),
(45, 'PHP post 9', 'Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668407227.jpg', '12', '5', '2022-11-14 12:27:07', 'php, test', 0, '1'),
(46, 'Java post 1', 'Java post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668408221.jpg', '13', '6', '2022-11-14 12:43:41', 'java, post, text, new, my', 0, '1'),
(47, 'Java post 2', 'Java post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668408248.PNG', '13', '6', '2022-11-14 12:44:08', 'java, post, text, new, my', 0, '1'),
(48, 'Java post 3', 'Java post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668408299.jpg', '13', '6', '2022-11-14 12:44:59', 'java, post, text, new, my', 0, '1'),
(49, 'Java post 4', 'Java post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668408502.jpg', '13', '3', '2022-11-14 12:48:22', 'java, test', 0, '1'),
(50, 'Java post 5', 'Java post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668408555.jpg', '13', '3', '2022-11-14 12:49:15', 'java, test', 0, '1'),
(51, 'Java', 'Java post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668408593.jpg', '13', 'Munaim Khan', '2022-11-14 12:49:53', 'java,', 0, '0'),
(52, 'Java post 7', 'Java post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668408818.png', '13', '7', '2022-11-14 12:53:38', 'java, post, text, new, my', 0, '1'),
(53, 'Java post 8', 'Java post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668408901.png', '13', '5', '2022-11-14 12:55:01', 'java, test', 0, '1'),
(54, 'Java post 9', 'Java post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668408941.png', '13', '5', '2022-11-14 12:55:41', 'java, test', 0, '1'),
(55, 'Mysql post 1', 'Mysql post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409014.png', '25', '5', '2022-11-14 12:56:54', 'mysql, test', 0, '1'),
(56, 'Mysql post 2', 'Mysql post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409049.png', '25', '5', '2022-11-14 12:57:29', 'mysql, test', 0, '1'),
(57, 'Mysql post 3', 'Mysql post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409079.png', '25', '5', '2022-11-14 12:57:59', 'mysql, test', 0, '1'),
(58, 'Mysql post 4', 'Mysql post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409142.png', '25', '3', '2022-11-14 12:59:02', 'mysql, test', 0, '1'),
(59, 'Mysql post 5', 'Mysql post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409211.png', '25', '6', '2022-11-14 13:00:11', 'mysql, test', 0, '1'),
(60, 'Css post 1', 'Css post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409254.png', '26', '6', '2022-11-14 13:00:54', 'css, post', 0, '1'),
(61, 'Css post 2', 'Css post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409293.png', '26', '6', '2022-11-14 13:01:33', 'css, post', 0, '1'),
(62, 'Css post 3', 'Css post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409342.png', '26', '3', '2022-11-14 13:02:22', 'css, post', 0, '1');
INSERT INTO `tbl_post` (`id`, `posttitle`, `postcontent`, `postImg`, `catId`, `postedby`, `posttime`, `posttags`, `postview`, `poststatus`) VALUES
(63, 'Css post 5', 'Css post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409372.png', '26', '3', '2022-11-14 13:02:52', 'css, post', 0, '1'),
(64, 'Html post 1', 'Html post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409437.png', '27', '5', '2022-11-14 13:03:57', 'html, post, text', 0, '1'),
(65, 'Html post 2', 'Html post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409467.png', '27', '5', '2022-11-14 13:04:27', 'html, post, text', 0, '1'),
(66, 'Java post 10', 'Java post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. \r\n\r\nPhp post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here. Php post content will be go here.', '1668409601.png', '13', '5', '2022-11-14 13:06:41', 'java, post, text, new, my', 0, '1');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `userId` bigint(20) UNSIGNED NOT NULL,
  `firstname` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastname` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `about` mediumtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `userImg` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` tinyint(4) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`userId`, `firstname`, `lastname`, `email`, `password`, `phone`, `about`, `userImg`, `role`) VALUES
(1, 'Md. Munaim', 'Khan', 'khanmail25@gmail.com', '$2y$10$UhVCr7vAfKR8L20puLu5zeID7eVQx5MmTKnvXSTWe/vtvK9HTtJ0O', '01826116163', 'Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. \r\n\r\nHi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project. Hi, i am Munaim Khan. Admin of my first laravel blog project.', '1668176424.jpg', 2),
(3, 'Tanim', 'Ahmed', 'tanim@gmail.com', '$2y$10$UhVCr7vAfKR8L20puLu5zeID7eVQx5MmTKnvXSTWe/vtvK9HTtJ0O', '01234-343432', 'About user will be go here. About user will be go here. About user will be go here. About user will be go here. About user will be go here. About user will be go here. About user will be go here. About user will be go here. About user will be go here. About user will be go here. About user will be go here. About user will be go here. About user will be go here. About user will be go here. ', '', 1),
(5, 'Rashedul', 'Karim', 'rashed@gmail.com', '$2y$10$uYIKDU5zlGI8JbDP7DjBmexCsfFDzY.WaOQTxRFbOZUCTLWDTHBOa', '01323-434345', NULL, NULL, 1),
(6, 'Raihanul', 'Islam', 'raihan@yahoo.com', '$2y$10$NW.g.Nf4WLSJzy3EnL6lP.9K8.IFXpTLqVWZvuz7GeXd/Wg88hEdi', '01234-543636', NULL, NULL, 1),
(7, 'Shahriar', 'Mahmud', 'mahmud@gmail.com', '$2y$10$Xm3ouTmiIgwIr6vAObF1Y.0Fz3rYhvd.zLDZzW4hoviElipz2QCGC', '01234-546789', NULL, NULL, 1),
(8, 'Md.', 'Khan', 'khanmail2599@gmail.com', '$2y$10$MwvLa0paa3E8CdNQeiX.Ze20eWIsHCRImkJlMsrPC8buD7UaooWeK', '01826116163', NULL, NULL, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  ADD KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`);

--
-- Indexes for table `tbl_category`
--
ALTER TABLE `tbl_category`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_comment`
--
ALTER TABLE `tbl_comment`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_message`
--
ALTER TABLE `tbl_message`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_post`
--
ALTER TABLE `tbl_post`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`userId`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `tbl_category`
--
ALTER TABLE `tbl_category`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;

--
-- AUTO_INCREMENT for table `tbl_comment`
--
ALTER TABLE `tbl_comment`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT for table `tbl_message`
--
ALTER TABLE `tbl_message`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;

--
-- AUTO_INCREMENT for table `tbl_post`
--
ALTER TABLE `tbl_post`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=67;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `userId` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
